name: Deploy Python App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PEM file from GitHub Secrets
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem  # Ensure proper permissions for the key

      - name: SSH into EC2
        run: |
          ssh -i ec2-key.pem -tt ubuntu@ec2-3-92-190-141.compute-1.amazonaws.com 

      - name: Deploy to EC2
        run: |
          cd trole
          source .venv/bin/activate
          git pull --no-edit origin main
          sudo systemctl restart gunicorn