name: Deploy Python App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PEM file from GitHub Secrets
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > trole-backend-aws.pem
          chmod 400 trole-backend-aws.pem  # Ensure proper permissions for the key

      - name: Add EC2 instance to known hosts
        run: |
          # Retrieve the EC2 public key and add it to known_hosts
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh 
          ssh-keyscan -H ec2-3-92-190-141.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy
        run: |
          ssh -i trole-backend-aws.pem ubuntu@ec2-3-92-190-141.compute-1.amazonaws.com << 'EOF'
            cd trole && \
            source .venv/bin/activate && \
            git pull --no-edit origin main && \
            sudo systemctl restart gunicorn
          EOF

