name: Deploy Python App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PEM file from GitHub Secrets
        run: |
          echo "$EC2_SSH_KEY" > trole-backend-aws.pem
          cat trole-backend-aws.pem
          chmod 400 trole-backend-aws.pem  # Ensure proper permissions for the key

      - name: SSH into EC2
        run: |
          ssh -i trole-backend-aws.pem -tt ubuntu@ec2-3-92-190-141.compute-1.amazonaws.com 

      - name: Deploy to EC2
        run: |
          cd trole
          source .venv/bin/activate
          git pull --no-edit origin main
          sudo systemctl restart gunicorn